(define (flush-token tokens current-token)
  (if (not (eq? (str-length current-token) 0))
      (append tokens (list current-token))
      tokens))

(define (tokenize-command cmd)
  (let ((tokens (list))
        (current-token "")
        (i 0)
        (in-single #f)
        (in-double #f)
        (len (str-length cmd)))
    (while (lt? i len)
      (let ((ch (str-char-at cmd i)))
        (cond
          (in-single
           (if (eq? ch "'")
               (begin
                 (set! tokens (append tokens (list current-token)))
                 (set! current-token "")
                 (set! in-single #f))
               (set! current-token (str-concat current-token ch))))
          (in-double
           (if (eq? ch "\"")
               (begin
                 (set! tokens (append tokens (list current-token)))
                 (set! current-token "")
                 (set! in-double #f))
               (set! current-token (str-concat current-token ch))))
          ((eq? ch "'") (set! in-single #t))
          ((eq? ch "\"") (set! in-double #t))
          ((or (eq? ch " ") (eq? ch "\t") (eq? ch "\n") (eq? ch "\r"))
           (set! tokens (flush-token tokens current-token))
           (set! current-token ""))
          ((or (eq? ch ";") (eq? ch "|") (eq? ch "<"))
           (set! tokens (flush-token tokens current-token))
           (set! current-token "")
           (set! tokens (append tokens (list ch))))
          ((eq? ch ">")
           (set! tokens (flush-token tokens current-token))
           (set! current-token "")
           (if (and (lt? (+ i 1) len)
                    (eq? (str-char-at cmd (+ i 1)) ">"))
               (begin
                 (set! tokens (append tokens (list ">>")))
                 (set! i (+ i 1)))
               (set! tokens (append tokens (list ">")))))
          (else
           (set! current-token (str-concat current-token ch)))))
      (set! i (+ i 1)))
    (set! tokens (flush-token tokens current-token))
    tokens))

(define command-table (list))

(define (register-command name handler)
  (set! command-table
        (append command-table (list (list name handler)))))

(define (lookup-command name)
  (let ((result #f))
    (for-each (lambda (entry)
                (when (eq? (list-ref entry 0) name)
                  (set! result (list-ref entry 1))))
              command-table)
    result))

(define (split-on-delimiter tokens delim)
  (let ((result (list))
        (current (list)))
    (for-each (lambda (tok)
                (if (eq? tok delim)
                    (begin
                      (when (not (eq? (length current) 0))
                        (set! result (append result (list current)))
                        (set! current (list))))
                    (set! current (append current (list tok)))))
              tokens)
    (when (not (eq? (length current) 0))
      (set! result (append result (list current))))
    result))

(define (expand-token tok)
  (cond
    ((string? tok)
     (cond
       ((eq? tok "~")
        (env-get "HOME"))
       ((and (gt? (str-length tok) 0)
             (eq? (str-substr tok 0 1) "$"))
        (let ((var-name (str-substr tok 1 (str-length tok))))
          (let ((val (env-get var-name)))
            (if val val ""))))
       (else tok)))
    (else tok)))

(define (dispatch-command cmdline)
  (history-add cmdline)
  (let ((tokens (tokenize-command cmdline)))
    (let ((segments (split-on-delimiter tokens ";"))
          (last-exit 0))
      (for-each (lambda (segment)
                  (let ((pipes (split-on-delimiter segment "|")))
                    (set! last-exit (execute-pipeline pipes))))
                segments)
      last-exit)))

(define (execute-pipeline segments)
  (let ((pipe-data "")
        (last-exit 0)
        (num-segs (length segments))
        (seg-idx 0))
    (for-each (lambda (seg)
                (set! seg-idx (+ seg-idx 1))
                (let ((is-last (eq? seg-idx num-segs)))
                  (let ((result (execute-single seg pipe-data is-last)))
                    (set! pipe-data (list-ref result 0))
                    (set! last-exit (list-ref result 1)))))
              segments)
    last-exit))

(define (execute-single tokens stdin is-last)
  (let ((expanded-tokens (map expand-token tokens)))
    (let ((redirect-out #f)
          (redirect-append #f)
          (redirect-in #f)
          (args (list))
          (command-name #f))
      (let ((i 0)
            (len (length expanded-tokens)))
        (while (lt? i len)
          (let ((tok (list-ref expanded-tokens i)))
            (cond
              ((eq? tok ">")
               (set! i (+ i 1))
               (when (lt? i len)
                 (set! redirect-out (list-ref expanded-tokens i))))
              ((eq? tok ">>")
               (set! i (+ i 1))
               (when (lt? i len)
                 (set! redirect-append (list-ref expanded-tokens i))))
              ((eq? tok "<")
               (set! i (+ i 1))
               (when (lt? i len)
                 (set! redirect-in (list-ref expanded-tokens i))))
              (else
               (if (not command-name)
                   (set! command-name tok)
                   (set! args (append args (list tok))))))
          (set! i (+ i 1))))
      (if (not command-name)
          (list "" 0)
          (let ((handler (lookup-command command-name)))
            (if handler
                (begin
                  (when redirect-in
                    (let ((content (fs-read redirect-in)))
                      (set! stdin content)))
                  (stdout-capture-start)
                  (let ((exit-code (handler args stdin)))
                    (let ((captured (stdout-capture-end)))
                      (cond
                        (redirect-out
                         (fs-write redirect-out captured)
                         (list "" 0))
                        (redirect-append
                         (let ((existing (if (fs-exists redirect-append)
                                             (fs-read redirect-append)
                                             "")))
                           (fs-write redirect-append (str-concat existing captured))
                           (list "" 0)))
                        (else
                         (when is-last (emit captured))
                         (list captured (if (number? exit-code) exit-code 0)))))))
                (begin
                  (emit-error (str-concat "bash: " command-name ": command not found"))
                  (list "" 127)))))))))
