"""Resolution pyramid for littlewing semantic overlays.

Builds a hierarchical view of session data at increasing abstraction:

    Level 0  — raw turns (the JSONL source, not generated)
    Level 1  — per-turn tightening: 1:1 transform, same turn count,
               noise stripped, signal preserved. Never merges turns.
    Level 2  — cross-connecting bridges: narrative links over groups
               of tightened turns, produced from temporal+size chunks.
    Level 3+ — bridges of bridges, recursively. Each level halves
               the material until the session is one coherent view.

Each level is:
  - Derived from the level below it
  - Generated by a stable system prompt (cached by DeepSeek)
  - Cached independently per session
  - Regenerable when the prompt or model improves

Prompt structure for cache efficiency:
  - System message: stable per level (cached by DeepSeek)
  - User message: variable per session/chunk (conversation content)
  DeepSeek caches the system message prefix across calls. Identical
  system prompts across sessions and chunks all share the cached prefix.
  Cache absorption may take two calls before hitting on the third.
"""

from __future__ import annotations

import json
import os
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

REPO_ROOT = Path(__file__).resolve().parent.parent
OVERLAYS_DIR = REPO_ROOT / "overlays"

# Sessions under this total char count skip Level 1 chunking
CHUNK_THRESHOLD = 40000

_OVERLAY_TYPES: dict[str, tuple] = {}


def overlay_type(name: str, description: str = ""):
    def decorator(fn):
        _OVERLAY_TYPES[name] = (fn, description)
        return fn
    return decorator


def list_types() -> dict[str, str]:
    return {name: desc for name, (_, desc) in _OVERLAY_TYPES.items()}


def get_overlay(
    session_id: str,
    project: str,
    overlay_name: str,
    turns: list[dict],
    metadata: dict,
    force: bool = False,
    model: Optional[str] = None,
) -> tuple[str, Path]:
    if overlay_name not in _OVERLAY_TYPES:
        raise ValueError(
            f"Unknown overlay type '{overlay_name}'. "
            f"Available: {', '.join(_OVERLAY_TYPES)}"
        )

    cache_dir = OVERLAYS_DIR / project / session_id[:8]
    cache_file = cache_dir / f"{overlay_name}.md"
    meta_file = cache_dir / f"_meta.json"

    if cache_file.exists() and not force:
        return cache_file.read_text(), cache_file

    gen_fn, _ = _OVERLAY_TYPES[overlay_name]
    content = gen_fn(turns, metadata, model=model)

    cache_dir.mkdir(parents=True, exist_ok=True)
    cache_file.write_text(content)
    _update_meta(meta_file, overlay_name, model)

    return content, cache_file


def _update_meta(meta_file: Path, overlay_name: str, model: Optional[str]):
    import llm
    meta = {}
    if meta_file.exists():
        try:
            meta = json.loads(meta_file.read_text())
        except (json.JSONDecodeError, OSError):
            pass

    meta[overlay_name] = {
        "model": model or llm._get_model(),
        "generated_at": datetime.now(timezone.utc).isoformat(),
    }
    meta_file.write_text(json.dumps(meta, indent=2) + "\n")


# ---------------------------------------------------------------------------
# Turn formatting — no truncation, ever
# ---------------------------------------------------------------------------

def _format_turns_numbered(turns: list[dict]) -> str:
    """Format turns with numbered labels for Level 1 processing.

    Output: [TURN N] [ROLE]: content
    One blank line between turns. No truncation.
    """
    lines = []
    for i, t in enumerate(turns):
        role = "USER" if t["role"] == "user" else "ASSISTANT"
        lines.append(f"[TURN {i + 1}] [{role}]: {t['text'].strip()}")
    return "\n\n".join(lines)


def _format_turns(turns: list[dict]) -> str:
    """Format turns into a string for LLM consumption. No truncation."""
    lines = []
    for t in turns:
        role = "USER" if t["role"] == "user" else "ASSISTANT"
        lines.append(f"[{role}]: {t['text'].strip()}\n")
    return "\n".join(lines)


def _needs_chunking(turns: list[dict]) -> bool:
    return sum(len(t.get("text", "")) for t in turns) > CHUNK_THRESHOLD


# ---------------------------------------------------------------------------
# Resolution pyramid — core pipeline
# ---------------------------------------------------------------------------

def build_pyramid(
    turns: list[dict],
    metadata: dict,
    max_level: int = 3,
    model: Optional[str] = None,
) -> dict[int, str]:
    """Build the resolution pyramid up to max_level.

    Returns {level: content} for each generated level.
    Level 0 is not included (it's the raw turns).
    """
    results = {}

    # Level 1: per-turn tightening
    l1 = _generate_level1(turns, metadata, model=model)
    results[1] = l1

    if max_level < 2:
        return results

    # Level 2: cross-connecting bridges over turn groups
    l2 = _generate_level2(l1, metadata, model=model)
    results[2] = l2

    # Level 3+: bridges of bridges, recursively
    current = l2
    for level in range(3, max_level + 1):
        synth = _generate_synthesis(current, level, metadata, model=model)
        results[level] = synth
        current = synth

    return results


def _generate_level1(
    turns: list[dict],
    metadata: dict,
    model: Optional[str] = None,
) -> str:
    """Level 1: Per-turn tightening. 1:1 transform, never merges turns."""
    import llm

    project = metadata.get("project", "unknown")

    if _needs_chunking(turns):
        return _level1_chunked(turns, metadata, model)

    conversation = _format_turns_numbered(turns)
    return llm.complete(
        [
            {"role": "system", "content": _SYSTEM_L1_TIGHTEN},
            {"role": "user", "content": (
                f"Project: {project}\n"
                f"Total turns: {len(turns)}\n\n"
                f"{conversation}"
            )},
        ],
        model=model,
        temperature=0.2,
    )


def _level1_chunked(
    turns: list[dict],
    metadata: dict,
    model: Optional[str] = None,
) -> str:
    """Level 1 over chunks — same system prompt every chunk (cache-friendly)."""
    import llm
    from chunking import chunk_turns, chunk_stats

    chunks = chunk_turns(turns)
    stats = chunk_stats(chunks)
    project = metadata.get("project", "unknown")

    print(
        f"  L1 chunked: {stats['num_chunks']} chunks, "
        f"sizes {stats['chunk_sizes']}",
        file=sys.stderr,
    )

    # Track global turn numbering across chunks
    results = []
    turn_offset = 0
    for i, chunk in enumerate(chunks):
        # Number turns globally, not per-chunk
        numbered_lines = []
        for j, t in enumerate(chunk):
            role = "USER" if t["role"] == "user" else "ASSISTANT"
            global_num = turn_offset + j + 1
            numbered_lines.append(
                f"[TURN {global_num}] [{role}]: {t['text'].strip()}"
            )
        conversation = "\n\n".join(numbered_lines)

        result = llm.complete(
            [
                {"role": "system", "content": _SYSTEM_L1_TIGHTEN},
                {"role": "user", "content": (
                    f"Project: {project}\n"
                    f"Chunk {i + 1} of {len(chunks)} "
                    f"(turns {turn_offset + 1}–{turn_offset + len(chunk)})\n\n"
                    f"{conversation}"
                )},
            ],
            model=model,
            temperature=0.2,
        )
        results.append(result)
        turn_offset += len(chunk)
        print(f"  L1 chunk {i + 1}/{len(chunks)} done", file=sys.stderr)

    return "\n\n".join(results)


def _generate_level2(
    l1_content: str,
    metadata: dict,
    model: Optional[str] = None,
) -> str:
    """Level 2: Cross-connecting bridges over groups of tightened turns."""
    import llm

    project = metadata.get("project", "unknown")

    # For small sessions, bridge in one pass
    if len(l1_content) <= CHUNK_THRESHOLD:
        return llm.complete(
            [
                {"role": "system", "content": _SYSTEM_L2_BRIDGE},
                {"role": "user", "content": (
                    f"Project: {project}\n\n"
                    f"Tightened turns:\n\n{l1_content}"
                )},
            ],
            model=model,
            temperature=0.2,
        )

    # For large sessions, split L1 output at turn boundaries and bridge
    # each segment separately, then join
    segments = _split_l1_at_boundaries(l1_content)
    print(
        f"  L2: {len(segments)} segments from L1 output",
        file=sys.stderr,
    )

    bridges = []
    for i, segment in enumerate(segments):
        result = llm.complete(
            [
                {"role": "system", "content": _SYSTEM_L2_BRIDGE},
                {"role": "user", "content": (
                    f"Project: {project}\n"
                    f"Segment {i + 1} of {len(segments)}\n\n"
                    f"Tightened turns:\n\n{segment}"
                )},
            ],
            model=model,
            temperature=0.2,
        )
        bridges.append(result)
        print(f"  L2 segment {i + 1}/{len(segments)} done", file=sys.stderr)

    return "\n\n---\n\n".join(bridges)


def _split_l1_at_boundaries(l1_content: str, target_size: int = 30000) -> list[str]:
    """Split Level 1 output into segments at turn boundaries.

    Never bisects a turn. Splits at blank lines between [TURN N] entries.
    """
    lines = l1_content.split("\n")
    segments = []
    current = []
    current_size = 0

    for line in lines:
        current.append(line)
        current_size += len(line) + 1

        # Split at turn boundaries (blank line before a [TURN ...] line)
        if (current_size >= target_size
                and line.strip() == ""
                and len(current) > 1):
            segments.append("\n".join(current))
            current = []
            current_size = 0

    if current:
        segments.append("\n".join(current))

    # If we ended up with just one segment, return it as-is
    return segments if len(segments) > 1 else [l1_content]


def _generate_synthesis(
    lower_content: str,
    level: int,
    metadata: dict,
    model: Optional[str] = None,
) -> str:
    """Level 3+: Synthesize lower-level bridges into higher-level bridges."""
    import llm

    project = metadata.get("project", "unknown")

    return llm.complete(
        [
            {"role": "system", "content": _SYSTEM_L3_SYNTHESIS},
            {"role": "user", "content": (
                f"Project: {project}\n"
                f"Pyramid level: {level} "
                f"(synthesizing level {level - 1} bridges)\n\n"
                f"{lower_content}"
            )},
        ],
        model=model,
        temperature=0.2,
    )


# ---------------------------------------------------------------------------
# System prompts — stable across calls, cached by DeepSeek
# ---------------------------------------------------------------------------
# These MUST NOT be mutated or interpolated with variable data.
# Cache hits depend on byte-identical prefixes.

_SYSTEM_L1_TIGHTEN = """\
You are a conversation compressor for an AI coding workflow. You receive
a segment of recorded conversation turns between a human developer and
an AI coding assistant.

Your task: produce a tightened version of EACH turn. This is a 1:1
transform — every input turn produces exactly one output turn. Never
merge turns. Never drop turns. Never reorder turns. The output must
have exactly as many turns as the input.

For each turn, strip:
- Verbose tool output and raw terminal dumps (keep the conclusion)
- Repeated failed attempts (keep only the successful path and what
  was learned from failures)
- Session-start boilerplate and pleasantries
- Redundant re-explanations of things already established
- Meta-commentary about the process itself (unless it produced a rule)
- Filler words and hedging that add no information

Preserve with full fidelity:
- File paths, function names, error messages, identifiers — verbatim
- Decisions and their rationale (the WHY, not just the WHAT)
- State changes: what was modified, created, deleted, configured
- Rules, conventions, constraints, or patterns established
- Open questions, blockers, unresolved issues
- Emotional signals from the human (frustration, emphasis, urgency)
  — these carry intent that affects downstream decisions

Output format — use this exactly:

[TURN N] [ROLE]: tightened content here

Where N is the original turn number (preserved from input) and ROLE is
USER or ASSISTANT. Each turn's content is a single continuous paragraph.
Separate turns with exactly one blank line.

Quality standard: a reader of your output should be able to reconstruct
every decision and state change from the original conversation. If
removing a detail would make any decision seem unmotivated or any state
change seem unexplained, that detail is load-bearing — keep it.

No preamble. No meta-commentary. Start directly with [TURN 1]."""

_SYSTEM_L2_BRIDGE = """\
You are a context bridge generator for an AI coding workflow. You receive
a sequence of tightened conversation turns (already compressed from raw)
and produce cross-connecting bridges that link groups of turns into
coherent narrative segments.

A bridge covers a group of related turns and synthesizes their combined
meaning. It answers: what was being worked on, what decisions were made,
what changed, and what was learned. Each bridge is a self-contained
alternative view — someone reading only the bridges should understand the
session's trajectory without needing individual turns.

A bridge is NOT a summary. It preserves the narrative thread and causal
chain. "We tried X, which revealed Y (a bug in Z), leading to decision W
and the creation of file F" is a bridge. "Various approaches were explored
and a solution was found" is waste.

How to group turns into bridges:
- Group by conceptual thread, not by fixed count
- A new bridge starts when the topic shifts materially
- A debugging sequence is one bridge even if it spans 15 turns
- A single turn that establishes a major decision is its own bridge

Preserve with full fidelity:
- File paths, function names, identifiers, error specifics
- The causal chain: what led to what, and why
- Decisions with enough rationale to not re-derive them
- Current state of work at the end of each bridge's scope
- What was tried and abandoned, with why (prevents re-exploration)

Output format — one markdown section per bridge:

## [Descriptive Topic Name]

Bridge narrative here. Present tense for current state ("the hook is
wired in settings.json"), past tense for completed work ("we fixed the
timestamp parsing by switching to fromisoformat").

No preamble. Start directly with the first ## heading."""

_SYSTEM_L3_SYNTHESIS = """\
You are a hierarchical synthesizer for an AI coding workflow. You receive
bridges from a lower level of a resolution pyramid — each bridge covers
a segment of a recorded conversation — and you produce a higher-level
bridge layer that connects them into broader narrative threads.

This is the same bridge operation applied one level up. The input bridges
are your raw material; group them by broader theme and produce bridges
that capture the session's arc at a higher altitude.

At this level, the reader wants to understand:
- What was the session about? (not "coding" — the specific problem space)
- What are the major outcomes? (decisions, artifacts, state changes)
- What is unfinished? (open threads, blockers, next steps)

Preserve every concrete detail needed to continue the work: file paths,
decisions and their rationale, current system state, open threads. A
detail that disappears at this level is a detail someone will re-derive
from scratch.

Discard: intermediate debugging steps already captured by lower bridges,
redundant restatements of the same decision across bridges, process
meta-commentary.

Output format: markdown sections with descriptive topic headings.

## [Broad Theme]

Synthesis narrative here.

No preamble. Start directly with the first ## heading."""


# Legacy prompts — kept for standalone overlay types that don't use the pyramid

_SYSTEM_DECISIONS = """\
You are a decision registry extractor for an AI coding workflow. You analyze
recorded conversations and extract every design decision — a choice between
alternatives that affects the codebase, architecture, or process.

A "decision" is not a routine implementation step. "Used a for loop" is not
a decision. "Chose SQLite over Postgres because the data is local-only" is.

Think deeply about each candidate decision. Consider whether it represents a
genuine fork in the road where a different choice would have led to
materially different code, architecture, or behavior.

For each decision, record:
- **What** was decided (one line, precise)
- **Why** — the reasoning or constraint that drove it
- **Alternatives** considered, if discussed (or "none discussed")
- **Where** it manifests (file path, config key, code pattern)

Format as a numbered markdown list. If no meaningful decisions were made,
say so in one line.

No preamble. Start directly with the list or the "no decisions" line."""


# ---------------------------------------------------------------------------
# Built-in overlay types
# ---------------------------------------------------------------------------

@overlay_type("l1_tighten", "Level 1: per-turn tightening (1:1 transform)")
def generate_l1(turns, metadata, model=None):
    return _generate_level1(turns, metadata, model=model)


@overlay_type("l2_bridge", "Level 2: cross-connecting bridges over turn groups")
def generate_l2(turns, metadata, model=None):
    l1 = _generate_level1(turns, metadata, model=model)
    return _generate_level2(l1, metadata, model=model)


@overlay_type("summary", "Full pyramid: tighten → bridge → synthesize")
def generate_summary(turns, metadata, model=None):
    pyramid = build_pyramid(turns, metadata, max_level=3, model=model)
    # Return the highest level produced
    return pyramid[max(pyramid)]


@overlay_type("bridge", "Compressed context bridge for session-start loading")
def generate_bridge(turns, metadata, model=None):
    # Bridge is Level 2 — cross-connecting bridges over tightened turns
    l1 = _generate_level1(turns, metadata, model=model)
    return _generate_level2(l1, metadata, model=model)


@overlay_type("decisions", "Registry of decisions made in this session")
def generate_decisions(turns, metadata, model=None):
    import llm

    # Decisions extraction runs on Level 1 output — tightened turns
    # are cleaner input than raw, and the system prompt is independent
    l1 = _generate_level1(turns, metadata, model=model)
    project = metadata.get("project", "unknown")

    return llm.complete(
        [
            {"role": "system", "content": _SYSTEM_DECISIONS},
            {"role": "user", "content": f"Project: {project}\n\n{l1}"},
        ],
        model=model,
        temperature=0.1,
    )


@overlay_type("pyramid", "Full resolution pyramid — all levels, concatenated")
def generate_pyramid_overlay(turns, metadata, model=None):
    pyramid = build_pyramid(turns, metadata, max_level=3, model=model)

    sections = []
    level_names = {1: "Per-Turn Tightening", 2: "Cross-Connecting Bridges",
                   3: "Session Synthesis"}
    for level in sorted(pyramid):
        name = level_names.get(level, f"Level {level}")
        sections.append(f"# Level {level}: {name}\n\n{pyramid[level]}")

    return "\n\n---\n\n".join(sections)
